"""Public API for 06 advanced graph-aware RAG."""

from __future__ import annotations

from legal_rag.oracle_context_evaluation.llm import UtopiaStructuredChatClient, resolve_ollama_chat_url
from legal_rag.oracle_context_evaluation.scoring import aggregate_results, score_mcq_label

from .models import (
    ADVANCED_RAG_PROMPT_VERSION,
    ADVANCED_RAG_SCHEMA_VERSION,
    AdvancedMcqAnswerOutput,
    AdvancedMcqResultRow,
    AdvancedNoHintAnswerOutput,
    AdvancedNoHintResultRow,
    AdvancedRagConfig,
    GraphRelationUsed,
    InteractiveRagConfig,
    InteractiveRagResult,
    InteractiveStepTiming,
    RerankOutput,
    RerankScore,
)
from .interactive import InteractiveRagRuntime, answer_interactive_question, build_interactive_runtime
from .retrieval import (
    GraphIndex,
    connect_qdrant,
    dense_vector_name,
    embed_sparse_query,
    expand_with_graph,
    load_index_manifest,
    load_simple_rag_manifest,
    resolve_collection_name,
    search_dense,
    search_hybrid,
    resolve_qdrant_target,
    sparse_vector_name,
)
from .runner import (
    build_advanced_query_embedder,
    build_context,
    build_diagnostics,
    build_quality_report,
    build_summary,
    resolve_answer_model,
    resolve_judge_model,
    resolve_utopia_runtime,
    run_advanced_graph_rag,
    run_mcq,
    run_no_hint,
    validate_qdrant_collection_ready,
)

__all__ = [
    "ADVANCED_RAG_PROMPT_VERSION",
    "ADVANCED_RAG_SCHEMA_VERSION",
    "AdvancedMcqAnswerOutput",
    "AdvancedMcqResultRow",
    "AdvancedNoHintAnswerOutput",
    "AdvancedNoHintResultRow",
    "AdvancedRagConfig",
    "GraphIndex",
    "GraphRelationUsed",
    "InteractiveRagConfig",
    "InteractiveRagResult",
    "InteractiveRagRuntime",
    "InteractiveStepTiming",
    "RerankOutput",
    "RerankScore",
    "UtopiaStructuredChatClient",
    "aggregate_results",
    "answer_interactive_question",
    "build_advanced_query_embedder",
    "build_context",
    "build_diagnostics",
    "build_quality_report",
    "build_summary",
    "build_interactive_runtime",
    "connect_qdrant",
    "dense_vector_name",
    "embed_sparse_query",
    "expand_with_graph",
    "load_index_manifest",
    "load_simple_rag_manifest",
    "resolve_answer_model",
    "resolve_judge_model",
    "resolve_ollama_chat_url",
    "resolve_collection_name",
    "resolve_qdrant_target",
    "resolve_utopia_runtime",
    "run_advanced_graph_rag",
    "run_mcq",
    "run_no_hint",
    "score_mcq_label",
    "search_dense",
    "search_hybrid",
    "sparse_vector_name",
    "validate_qdrant_collection_ready",
]
