"""Qdrant indexing pipeline for laws_dataset_clean."""

from .chunk_refinement import (
    ChunkRefinementDiagnostics,
    RefinedChunk,
    passage_order_key,
    refine_chunks,
    refine_chunks_with_diagnostics,
)
from .embeddings import (
    AutoUtopiaEmbedder,
    LangChainUtopiaEmbedder,
    SupportsEmbedding,
    UtopiaOllamaEmbedder,
    build_embedder,
    discover_utopia_models,
    debug_utopia_embedding_connection,
)
from .io import (
    DatasetBundle,
    DatasetValidationResult,
    PassageRecord,
    article_sort_key,
    build_article_order_map,
    dataset_hash_from_manifest,
    load_dataset_bundle,
    reconstruct_passages,
    validate_dataset,
)
from .pipeline import IndexingRunSummary, run_indexing_pipeline
from .law_references import (
    EvalCoverageReport,
    LawCatalog,
    LawReferenceMention,
    LawReferenceResolution,
    build_law_catalog,
    compute_eval_reference_coverage,
    extract_law_reference_mentions,
    load_eval_reference_texts,
    resolve_law_references,
)
from .rag_runtime import (
    QdrantPayloadFieldMap,
    RagRuntimeConfig,
    build_rag_graph,
    prepare_runtime,
    run_rag_question,
)
from .settings import ChunkingProfile, IndexingConfig, make_chunking_profile

__all__ = [
    "ChunkingProfile",
    "IndexingConfig",
    "make_chunking_profile",
    "DatasetValidationResult",
    "DatasetBundle",
    "PassageRecord",
    "article_sort_key",
    "build_article_order_map",
    "dataset_hash_from_manifest",
    "reconstruct_passages",
    "validate_dataset",
    "RefinedChunk",
    "ChunkRefinementDiagnostics",
    "passage_order_key",
    "refine_chunks",
    "refine_chunks_with_diagnostics",
    "SupportsEmbedding",
    "LangChainUtopiaEmbedder",
    "UtopiaOllamaEmbedder",
    "AutoUtopiaEmbedder",
    "discover_utopia_models",
    "build_embedder",
    "debug_utopia_embedding_connection",
    "IndexingRunSummary",
    "run_indexing_pipeline",
    "LawReferenceMention",
    "LawReferenceResolution",
    "LawCatalog",
    "EvalCoverageReport",
    "build_law_catalog",
    "extract_law_reference_mentions",
    "resolve_law_references",
    "load_eval_reference_texts",
    "compute_eval_reference_coverage",
    "QdrantPayloadFieldMap",
    "RagRuntimeConfig",
    "prepare_runtime",
    "build_rag_graph",
    "run_rag_question",
]
