from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, field_validator


MCQ_LABELS = ("A", "B", "C", "D", "E", "F")
JUDGE_LABELS = (*MCQ_LABELS, "NONE")


class RagAnswer(BaseModel):
    """Structured answer generated by the naive RAG pipeline."""

    model_config = ConfigDict(extra="forbid")

    answer: str = Field(default="")
    citations: list[str] = Field(default_factory=list)
    needs_more_context: bool = Field(default=False)

    @field_validator("answer", mode="before")
    @classmethod
    def _normalize_answer(cls, value: Any) -> str:
        if value is None:
            return ""
        return str(value).strip()

    @field_validator("citations", mode="before")
    @classmethod
    def _coerce_citations(cls, value: Any) -> list[str]:
        if value is None:
            return []
        if not isinstance(value, list):
            value = [value]

        out: list[str] = []
        for item in value:
            if isinstance(item, dict):
                # Common variants returned by LLMs/tools:
                # {"chunk_id": "..."} or {"source": "..."} or {"id": "..."}.
                for key in ("chunk_id", "source", "id"):
                    raw = item.get(key)
                    if raw is not None:
                        text = str(raw).strip()
                        if text:
                            out.append(text)
                            break
            else:
                text = str(item or "").strip()
                if text:
                    out.append(text)
        return out

    @field_validator("citations", mode="after")
    @classmethod
    def _normalize_citations(cls, value: list[str]) -> list[str]:
        out: list[str] = []
        seen: set[str] = set()
        for item in value:
            cur = str(item or "").strip()
            if not cur or cur in seen:
                continue
            seen.add(cur)
            out.append(cur)
        return out


class NoHintAnswer(BaseModel):
    """Structured answer for open-question evaluation before judging."""

    model_config = ConfigDict(extra="forbid")

    answer_text: str = Field(default="")
    short_rationale: str | None = None

    @field_validator("answer_text")
    @classmethod
    def _normalize_answer_text(cls, value: str) -> str:
        return (value or "").strip()


class McqAnswer(BaseModel):
    """Structured MCQ output used in evaluation."""

    model_config = ConfigDict(extra="forbid")

    answer_label: str
    short_rationale: str | None = None

    @field_validator("answer_label")
    @classmethod
    def _normalize_label(cls, value: str) -> str:
        label = (value or "").strip().upper()
        if label not in MCQ_LABELS:
            raise ValueError(f"Unsupported label: {value!r}")
        return label


class JudgeResult(BaseModel):
    """Structured result for no-hint semantic judge (0/1)."""

    model_config = ConfigDict(extra="forbid")

    score: Literal[0, 1]
    confidence: float = Field(ge=0.0, le=1.0)
    matched_option_label: str
    is_semantically_equivalent: bool
    justification: str = Field(default="")

    @field_validator("matched_option_label")
    @classmethod
    def _normalize_matched_label(cls, value: str) -> str:
        label = (value or "").strip().upper()
        if label not in JUDGE_LABELS:
            raise ValueError(f"Unsupported matched_option_label: {value!r}")
        return label

    @field_validator("justification")
    @classmethod
    def _normalize_justification(cls, value: str) -> str:
        return (value or "").strip()


def schema_to_json_dict(model_cls: type[BaseModel]) -> dict[str, Any]:
    """Return JSON schema as a plain dict for API `format` payloads."""

    return model_cls.model_json_schema()


def ensure_model(model_cls: type[BaseModel], data: Any) -> BaseModel:
    """Validate arbitrary data with a Pydantic model and return a model instance."""

    return model_cls.model_validate(data)
